/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as AboutImport } from './routes/about'
import { Route as IdRouteImport } from './routes/$id/route'
import { Route as IndexImport } from './routes/index'
import { Route as IdIndexImport } from './routes/$id/index'
import { Route as IdWasteRecordImport } from './routes/$id/wasteRecord'
import { Route as IdUsersImport } from './routes/$id/users'
import { Route as IdTransferRecordImport } from './routes/$id/transferRecord'
import { Route as IdTimeSheetImport } from './routes/$id/timeSheet'
import { Route as IdSupplierImport } from './routes/$id/supplier'
import { Route as IdStorageAreaImport } from './routes/$id/storageArea'
import { Route as IdStockLocationImport } from './routes/$id/stockLocation'
import { Route as IdSalesTransactionImport } from './routes/$id/salesTransaction'
import { Route as IdRestaurantImport } from './routes/$id/restaurant'
import { Route as IdRecipeIngredintImport } from './routes/$id/recipeIngredint'
import { Route as IdRecipeImport } from './routes/$id/recipe'
import { Route as IdPurchaseOrderImport } from './routes/$id/purchaseOrder'
import { Route as IdProductsImport } from './routes/$id/products'
import { Route as IdOwnerImport } from './routes/$id/owner'
import { Route as IdOrdersImport } from './routes/$id/orders'
import { Route as IdLineItemImport } from './routes/$id/lineItem'
import { Route as IdInventoryImport } from './routes/$id/inventory'
import { Route as IdIngredientImport } from './routes/$id/ingredient'
import { Route as IdBusinessesImport } from './routes/$id/businesses'
import { Route as IdAssetsImport } from './routes/$id/assets'
import { Route as IdAssetMaintenanceImport } from './routes/$id/assetMaintenance'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IdRouteRoute = IdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const IdIndexRoute = IdIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IdRouteRoute,
} as any)

const IdWasteRecordRoute = IdWasteRecordImport.update({
  id: '/wasteRecord',
  path: '/wasteRecord',
  getParentRoute: () => IdRouteRoute,
} as any)

const IdUsersRoute = IdUsersImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => IdRouteRoute,
} as any)

const IdTransferRecordRoute = IdTransferRecordImport.update({
  id: '/transferRecord',
  path: '/transferRecord',
  getParentRoute: () => IdRouteRoute,
} as any)

const IdTimeSheetRoute = IdTimeSheetImport.update({
  id: '/timeSheet',
  path: '/timeSheet',
  getParentRoute: () => IdRouteRoute,
} as any)

const IdSupplierRoute = IdSupplierImport.update({
  id: '/supplier',
  path: '/supplier',
  getParentRoute: () => IdRouteRoute,
} as any)

const IdStorageAreaRoute = IdStorageAreaImport.update({
  id: '/storageArea',
  path: '/storageArea',
  getParentRoute: () => IdRouteRoute,
} as any)

const IdStockLocationRoute = IdStockLocationImport.update({
  id: '/stockLocation',
  path: '/stockLocation',
  getParentRoute: () => IdRouteRoute,
} as any)

const IdSalesTransactionRoute = IdSalesTransactionImport.update({
  id: '/salesTransaction',
  path: '/salesTransaction',
  getParentRoute: () => IdRouteRoute,
} as any)

const IdRestaurantRoute = IdRestaurantImport.update({
  id: '/restaurant',
  path: '/restaurant',
  getParentRoute: () => IdRouteRoute,
} as any)

const IdRecipeIngredintRoute = IdRecipeIngredintImport.update({
  id: '/recipeIngredint',
  path: '/recipeIngredint',
  getParentRoute: () => IdRouteRoute,
} as any)

const IdRecipeRoute = IdRecipeImport.update({
  id: '/recipe',
  path: '/recipe',
  getParentRoute: () => IdRouteRoute,
} as any)

const IdPurchaseOrderRoute = IdPurchaseOrderImport.update({
  id: '/purchaseOrder',
  path: '/purchaseOrder',
  getParentRoute: () => IdRouteRoute,
} as any)

const IdProductsRoute = IdProductsImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => IdRouteRoute,
} as any)

const IdOwnerRoute = IdOwnerImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => IdRouteRoute,
} as any)

const IdOrdersRoute = IdOrdersImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => IdRouteRoute,
} as any)

const IdLineItemRoute = IdLineItemImport.update({
  id: '/lineItem',
  path: '/lineItem',
  getParentRoute: () => IdRouteRoute,
} as any)

const IdInventoryRoute = IdInventoryImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => IdRouteRoute,
} as any)

const IdIngredientRoute = IdIngredientImport.update({
  id: '/ingredient',
  path: '/ingredient',
  getParentRoute: () => IdRouteRoute,
} as any)

const IdBusinessesRoute = IdBusinessesImport.update({
  id: '/businesses',
  path: '/businesses',
  getParentRoute: () => IdRouteRoute,
} as any)

const IdAssetsRoute = IdAssetsImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => IdRouteRoute,
} as any)

const IdAssetMaintenanceRoute = IdAssetMaintenanceImport.update({
  id: '/assetMaintenance',
  path: '/assetMaintenance',
  getParentRoute: () => IdRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$id': {
      id: '/$id'
      path: '/$id'
      fullPath: '/$id'
      preLoaderRoute: typeof IdRouteImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/$id/assetMaintenance': {
      id: '/$id/assetMaintenance'
      path: '/assetMaintenance'
      fullPath: '/$id/assetMaintenance'
      preLoaderRoute: typeof IdAssetMaintenanceImport
      parentRoute: typeof IdRouteImport
    }
    '/$id/assets': {
      id: '/$id/assets'
      path: '/assets'
      fullPath: '/$id/assets'
      preLoaderRoute: typeof IdAssetsImport
      parentRoute: typeof IdRouteImport
    }
    '/$id/businesses': {
      id: '/$id/businesses'
      path: '/businesses'
      fullPath: '/$id/businesses'
      preLoaderRoute: typeof IdBusinessesImport
      parentRoute: typeof IdRouteImport
    }
    '/$id/ingredient': {
      id: '/$id/ingredient'
      path: '/ingredient'
      fullPath: '/$id/ingredient'
      preLoaderRoute: typeof IdIngredientImport
      parentRoute: typeof IdRouteImport
    }
    '/$id/inventory': {
      id: '/$id/inventory'
      path: '/inventory'
      fullPath: '/$id/inventory'
      preLoaderRoute: typeof IdInventoryImport
      parentRoute: typeof IdRouteImport
    }
    '/$id/lineItem': {
      id: '/$id/lineItem'
      path: '/lineItem'
      fullPath: '/$id/lineItem'
      preLoaderRoute: typeof IdLineItemImport
      parentRoute: typeof IdRouteImport
    }
    '/$id/orders': {
      id: '/$id/orders'
      path: '/orders'
      fullPath: '/$id/orders'
      preLoaderRoute: typeof IdOrdersImport
      parentRoute: typeof IdRouteImport
    }
    '/$id/owner': {
      id: '/$id/owner'
      path: '/owner'
      fullPath: '/$id/owner'
      preLoaderRoute: typeof IdOwnerImport
      parentRoute: typeof IdRouteImport
    }
    '/$id/products': {
      id: '/$id/products'
      path: '/products'
      fullPath: '/$id/products'
      preLoaderRoute: typeof IdProductsImport
      parentRoute: typeof IdRouteImport
    }
    '/$id/purchaseOrder': {
      id: '/$id/purchaseOrder'
      path: '/purchaseOrder'
      fullPath: '/$id/purchaseOrder'
      preLoaderRoute: typeof IdPurchaseOrderImport
      parentRoute: typeof IdRouteImport
    }
    '/$id/recipe': {
      id: '/$id/recipe'
      path: '/recipe'
      fullPath: '/$id/recipe'
      preLoaderRoute: typeof IdRecipeImport
      parentRoute: typeof IdRouteImport
    }
    '/$id/recipeIngredint': {
      id: '/$id/recipeIngredint'
      path: '/recipeIngredint'
      fullPath: '/$id/recipeIngredint'
      preLoaderRoute: typeof IdRecipeIngredintImport
      parentRoute: typeof IdRouteImport
    }
    '/$id/restaurant': {
      id: '/$id/restaurant'
      path: '/restaurant'
      fullPath: '/$id/restaurant'
      preLoaderRoute: typeof IdRestaurantImport
      parentRoute: typeof IdRouteImport
    }
    '/$id/salesTransaction': {
      id: '/$id/salesTransaction'
      path: '/salesTransaction'
      fullPath: '/$id/salesTransaction'
      preLoaderRoute: typeof IdSalesTransactionImport
      parentRoute: typeof IdRouteImport
    }
    '/$id/stockLocation': {
      id: '/$id/stockLocation'
      path: '/stockLocation'
      fullPath: '/$id/stockLocation'
      preLoaderRoute: typeof IdStockLocationImport
      parentRoute: typeof IdRouteImport
    }
    '/$id/storageArea': {
      id: '/$id/storageArea'
      path: '/storageArea'
      fullPath: '/$id/storageArea'
      preLoaderRoute: typeof IdStorageAreaImport
      parentRoute: typeof IdRouteImport
    }
    '/$id/supplier': {
      id: '/$id/supplier'
      path: '/supplier'
      fullPath: '/$id/supplier'
      preLoaderRoute: typeof IdSupplierImport
      parentRoute: typeof IdRouteImport
    }
    '/$id/timeSheet': {
      id: '/$id/timeSheet'
      path: '/timeSheet'
      fullPath: '/$id/timeSheet'
      preLoaderRoute: typeof IdTimeSheetImport
      parentRoute: typeof IdRouteImport
    }
    '/$id/transferRecord': {
      id: '/$id/transferRecord'
      path: '/transferRecord'
      fullPath: '/$id/transferRecord'
      preLoaderRoute: typeof IdTransferRecordImport
      parentRoute: typeof IdRouteImport
    }
    '/$id/users': {
      id: '/$id/users'
      path: '/users'
      fullPath: '/$id/users'
      preLoaderRoute: typeof IdUsersImport
      parentRoute: typeof IdRouteImport
    }
    '/$id/wasteRecord': {
      id: '/$id/wasteRecord'
      path: '/wasteRecord'
      fullPath: '/$id/wasteRecord'
      preLoaderRoute: typeof IdWasteRecordImport
      parentRoute: typeof IdRouteImport
    }
    '/$id/': {
      id: '/$id/'
      path: '/'
      fullPath: '/$id/'
      preLoaderRoute: typeof IdIndexImport
      parentRoute: typeof IdRouteImport
    }
  }
}

// Create and export the route tree

interface IdRouteRouteChildren {
  IdAssetMaintenanceRoute: typeof IdAssetMaintenanceRoute
  IdAssetsRoute: typeof IdAssetsRoute
  IdBusinessesRoute: typeof IdBusinessesRoute
  IdIngredientRoute: typeof IdIngredientRoute
  IdInventoryRoute: typeof IdInventoryRoute
  IdLineItemRoute: typeof IdLineItemRoute
  IdOrdersRoute: typeof IdOrdersRoute
  IdOwnerRoute: typeof IdOwnerRoute
  IdProductsRoute: typeof IdProductsRoute
  IdPurchaseOrderRoute: typeof IdPurchaseOrderRoute
  IdRecipeRoute: typeof IdRecipeRoute
  IdRecipeIngredintRoute: typeof IdRecipeIngredintRoute
  IdRestaurantRoute: typeof IdRestaurantRoute
  IdSalesTransactionRoute: typeof IdSalesTransactionRoute
  IdStockLocationRoute: typeof IdStockLocationRoute
  IdStorageAreaRoute: typeof IdStorageAreaRoute
  IdSupplierRoute: typeof IdSupplierRoute
  IdTimeSheetRoute: typeof IdTimeSheetRoute
  IdTransferRecordRoute: typeof IdTransferRecordRoute
  IdUsersRoute: typeof IdUsersRoute
  IdWasteRecordRoute: typeof IdWasteRecordRoute
  IdIndexRoute: typeof IdIndexRoute
}

const IdRouteRouteChildren: IdRouteRouteChildren = {
  IdAssetMaintenanceRoute: IdAssetMaintenanceRoute,
  IdAssetsRoute: IdAssetsRoute,
  IdBusinessesRoute: IdBusinessesRoute,
  IdIngredientRoute: IdIngredientRoute,
  IdInventoryRoute: IdInventoryRoute,
  IdLineItemRoute: IdLineItemRoute,
  IdOrdersRoute: IdOrdersRoute,
  IdOwnerRoute: IdOwnerRoute,
  IdProductsRoute: IdProductsRoute,
  IdPurchaseOrderRoute: IdPurchaseOrderRoute,
  IdRecipeRoute: IdRecipeRoute,
  IdRecipeIngredintRoute: IdRecipeIngredintRoute,
  IdRestaurantRoute: IdRestaurantRoute,
  IdSalesTransactionRoute: IdSalesTransactionRoute,
  IdStockLocationRoute: IdStockLocationRoute,
  IdStorageAreaRoute: IdStorageAreaRoute,
  IdSupplierRoute: IdSupplierRoute,
  IdTimeSheetRoute: IdTimeSheetRoute,
  IdTransferRecordRoute: IdTransferRecordRoute,
  IdUsersRoute: IdUsersRoute,
  IdWasteRecordRoute: IdWasteRecordRoute,
  IdIndexRoute: IdIndexRoute,
}

const IdRouteRouteWithChildren =
  IdRouteRoute._addFileChildren(IdRouteRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$id': typeof IdRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/$id/assetMaintenance': typeof IdAssetMaintenanceRoute
  '/$id/assets': typeof IdAssetsRoute
  '/$id/businesses': typeof IdBusinessesRoute
  '/$id/ingredient': typeof IdIngredientRoute
  '/$id/inventory': typeof IdInventoryRoute
  '/$id/lineItem': typeof IdLineItemRoute
  '/$id/orders': typeof IdOrdersRoute
  '/$id/owner': typeof IdOwnerRoute
  '/$id/products': typeof IdProductsRoute
  '/$id/purchaseOrder': typeof IdPurchaseOrderRoute
  '/$id/recipe': typeof IdRecipeRoute
  '/$id/recipeIngredint': typeof IdRecipeIngredintRoute
  '/$id/restaurant': typeof IdRestaurantRoute
  '/$id/salesTransaction': typeof IdSalesTransactionRoute
  '/$id/stockLocation': typeof IdStockLocationRoute
  '/$id/storageArea': typeof IdStorageAreaRoute
  '/$id/supplier': typeof IdSupplierRoute
  '/$id/timeSheet': typeof IdTimeSheetRoute
  '/$id/transferRecord': typeof IdTransferRecordRoute
  '/$id/users': typeof IdUsersRoute
  '/$id/wasteRecord': typeof IdWasteRecordRoute
  '/$id/': typeof IdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/$id/assetMaintenance': typeof IdAssetMaintenanceRoute
  '/$id/assets': typeof IdAssetsRoute
  '/$id/businesses': typeof IdBusinessesRoute
  '/$id/ingredient': typeof IdIngredientRoute
  '/$id/inventory': typeof IdInventoryRoute
  '/$id/lineItem': typeof IdLineItemRoute
  '/$id/orders': typeof IdOrdersRoute
  '/$id/owner': typeof IdOwnerRoute
  '/$id/products': typeof IdProductsRoute
  '/$id/purchaseOrder': typeof IdPurchaseOrderRoute
  '/$id/recipe': typeof IdRecipeRoute
  '/$id/recipeIngredint': typeof IdRecipeIngredintRoute
  '/$id/restaurant': typeof IdRestaurantRoute
  '/$id/salesTransaction': typeof IdSalesTransactionRoute
  '/$id/stockLocation': typeof IdStockLocationRoute
  '/$id/storageArea': typeof IdStorageAreaRoute
  '/$id/supplier': typeof IdSupplierRoute
  '/$id/timeSheet': typeof IdTimeSheetRoute
  '/$id/transferRecord': typeof IdTransferRecordRoute
  '/$id/users': typeof IdUsersRoute
  '/$id/wasteRecord': typeof IdWasteRecordRoute
  '/$id': typeof IdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/$id': typeof IdRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/$id/assetMaintenance': typeof IdAssetMaintenanceRoute
  '/$id/assets': typeof IdAssetsRoute
  '/$id/businesses': typeof IdBusinessesRoute
  '/$id/ingredient': typeof IdIngredientRoute
  '/$id/inventory': typeof IdInventoryRoute
  '/$id/lineItem': typeof IdLineItemRoute
  '/$id/orders': typeof IdOrdersRoute
  '/$id/owner': typeof IdOwnerRoute
  '/$id/products': typeof IdProductsRoute
  '/$id/purchaseOrder': typeof IdPurchaseOrderRoute
  '/$id/recipe': typeof IdRecipeRoute
  '/$id/recipeIngredint': typeof IdRecipeIngredintRoute
  '/$id/restaurant': typeof IdRestaurantRoute
  '/$id/salesTransaction': typeof IdSalesTransactionRoute
  '/$id/stockLocation': typeof IdStockLocationRoute
  '/$id/storageArea': typeof IdStorageAreaRoute
  '/$id/supplier': typeof IdSupplierRoute
  '/$id/timeSheet': typeof IdTimeSheetRoute
  '/$id/transferRecord': typeof IdTransferRecordRoute
  '/$id/users': typeof IdUsersRoute
  '/$id/wasteRecord': typeof IdWasteRecordRoute
  '/$id/': typeof IdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$id'
    | '/about'
    | '/login'
    | '/$id/assetMaintenance'
    | '/$id/assets'
    | '/$id/businesses'
    | '/$id/ingredient'
    | '/$id/inventory'
    | '/$id/lineItem'
    | '/$id/orders'
    | '/$id/owner'
    | '/$id/products'
    | '/$id/purchaseOrder'
    | '/$id/recipe'
    | '/$id/recipeIngredint'
    | '/$id/restaurant'
    | '/$id/salesTransaction'
    | '/$id/stockLocation'
    | '/$id/storageArea'
    | '/$id/supplier'
    | '/$id/timeSheet'
    | '/$id/transferRecord'
    | '/$id/users'
    | '/$id/wasteRecord'
    | '/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/$id/assetMaintenance'
    | '/$id/assets'
    | '/$id/businesses'
    | '/$id/ingredient'
    | '/$id/inventory'
    | '/$id/lineItem'
    | '/$id/orders'
    | '/$id/owner'
    | '/$id/products'
    | '/$id/purchaseOrder'
    | '/$id/recipe'
    | '/$id/recipeIngredint'
    | '/$id/restaurant'
    | '/$id/salesTransaction'
    | '/$id/stockLocation'
    | '/$id/storageArea'
    | '/$id/supplier'
    | '/$id/timeSheet'
    | '/$id/transferRecord'
    | '/$id/users'
    | '/$id/wasteRecord'
    | '/$id'
  id:
    | '__root__'
    | '/'
    | '/$id'
    | '/about'
    | '/login'
    | '/$id/assetMaintenance'
    | '/$id/assets'
    | '/$id/businesses'
    | '/$id/ingredient'
    | '/$id/inventory'
    | '/$id/lineItem'
    | '/$id/orders'
    | '/$id/owner'
    | '/$id/products'
    | '/$id/purchaseOrder'
    | '/$id/recipe'
    | '/$id/recipeIngredint'
    | '/$id/restaurant'
    | '/$id/salesTransaction'
    | '/$id/stockLocation'
    | '/$id/storageArea'
    | '/$id/supplier'
    | '/$id/timeSheet'
    | '/$id/transferRecord'
    | '/$id/users'
    | '/$id/wasteRecord'
    | '/$id/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IdRouteRoute: typeof IdRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IdRouteRoute: IdRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$id",
        "/about",
        "/login"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$id": {
      "filePath": "$id/route.tsx",
      "children": [
        "/$id/assetMaintenance",
        "/$id/assets",
        "/$id/businesses",
        "/$id/ingredient",
        "/$id/inventory",
        "/$id/lineItem",
        "/$id/orders",
        "/$id/owner",
        "/$id/products",
        "/$id/purchaseOrder",
        "/$id/recipe",
        "/$id/recipeIngredint",
        "/$id/restaurant",
        "/$id/salesTransaction",
        "/$id/stockLocation",
        "/$id/storageArea",
        "/$id/supplier",
        "/$id/timeSheet",
        "/$id/transferRecord",
        "/$id/users",
        "/$id/wasteRecord",
        "/$id/"
      ]
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/$id/assetMaintenance": {
      "filePath": "$id/assetMaintenance.tsx",
      "parent": "/$id"
    },
    "/$id/assets": {
      "filePath": "$id/assets.tsx",
      "parent": "/$id"
    },
    "/$id/businesses": {
      "filePath": "$id/businesses.tsx",
      "parent": "/$id"
    },
    "/$id/ingredient": {
      "filePath": "$id/ingredient.tsx",
      "parent": "/$id"
    },
    "/$id/inventory": {
      "filePath": "$id/inventory.tsx",
      "parent": "/$id"
    },
    "/$id/lineItem": {
      "filePath": "$id/lineItem.tsx",
      "parent": "/$id"
    },
    "/$id/orders": {
      "filePath": "$id/orders.tsx",
      "parent": "/$id"
    },
    "/$id/owner": {
      "filePath": "$id/owner.tsx",
      "parent": "/$id"
    },
    "/$id/products": {
      "filePath": "$id/products.tsx",
      "parent": "/$id"
    },
    "/$id/purchaseOrder": {
      "filePath": "$id/purchaseOrder.tsx",
      "parent": "/$id"
    },
    "/$id/recipe": {
      "filePath": "$id/recipe.tsx",
      "parent": "/$id"
    },
    "/$id/recipeIngredint": {
      "filePath": "$id/recipeIngredint.tsx",
      "parent": "/$id"
    },
    "/$id/restaurant": {
      "filePath": "$id/restaurant.tsx",
      "parent": "/$id"
    },
    "/$id/salesTransaction": {
      "filePath": "$id/salesTransaction.tsx",
      "parent": "/$id"
    },
    "/$id/stockLocation": {
      "filePath": "$id/stockLocation.tsx",
      "parent": "/$id"
    },
    "/$id/storageArea": {
      "filePath": "$id/storageArea.tsx",
      "parent": "/$id"
    },
    "/$id/supplier": {
      "filePath": "$id/supplier.tsx",
      "parent": "/$id"
    },
    "/$id/timeSheet": {
      "filePath": "$id/timeSheet.tsx",
      "parent": "/$id"
    },
    "/$id/transferRecord": {
      "filePath": "$id/transferRecord.tsx",
      "parent": "/$id"
    },
    "/$id/users": {
      "filePath": "$id/users.tsx",
      "parent": "/$id"
    },
    "/$id/wasteRecord": {
      "filePath": "$id/wasteRecord.tsx",
      "parent": "/$id"
    },
    "/$id/": {
      "filePath": "$id/index.tsx",
      "parent": "/$id"
    }
  }
}
ROUTE_MANIFEST_END */
